// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"time"
)

func Store() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><head><link rel=\"stylesheet\" href=\"../assets/styles/styles.css\"></head><body><fieldset><legend>Product Information</legend><div class=\"form-container\"><div class=\"form-fields\"><form action=\"/purchase\" method=\"post\"><label for=\"firstName\">First Name*:</label> <input type=\"text\" id=\"firstName\" name=\"firstName\" required pattern=\"[A-Za-z\\s&#39;]+\"> <label for=\"lastName\">Last Name*:</label> <input type=\"text\" id=\"lastName\" name=\"lastName\" required pattern=\"[A-Za-z\\s&#39;]+\"> <label for=\"email\">Email*:</label> <input type=\"email\" id=\"email\" name=\"email\" required> <label for=\"product\">Product*:</label> <select id=\"product\" name=\"product\" required onchange=\"showProductImage()\"><option value=\"\">Select an item</option> <option value=\"Spoon\">Spoon - $1.00</option> <option value=\"Fork\">Fork - $1.50</option> <option value=\"Knife\">Knife - $2.00</option></select> <label for=\"quantity\">Quantity*:</label> <input type=\"number\" id=\"quantity\" name=\"quantity\" min=\"1\" max=\"100\" required> <label>Would you like to round up for a donation?</label> <label><input type=\"radio\" name=\"donation\" value=\"yes\"> Yes</label> <label><input type=\"radio\" name=\"donation\" value=\"no\" checked> No</label> <input type=\"hidden\" name=\"timestamp\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", time.Now().Unix()))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/store.templ`, Line: 45, Col: 106}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"> <button type=\"submit\">Purchase</button></form></div><div class=\"product-image\"><h3 id=\"productTitle\">Select product to see image</h3><img id=\"productImage\" src=\"\" alt=\"Product image\"></div></div></fieldset></body><script>\n        function showProductImage() {\n            const productSelect = document.getElementById(\"product\");\n            const productImage = document.getElementById(\"productImage\");\n            const product = productSelect.value;\n            const productImages = {\n                \"Spoon\": \"assets/images/spoon.jpeg\",\n                \"Fork\": \"assets/images/fork.jpeg\",\n                \"Knife\": \"assets/images/knife.jpeg\"\n            };\n\n            if (product) {\n                productImage.src = productImages[product];\n                productImage.alt = product + \" image\"; \n            } else {\n                productImage.src = \"\"; \n                productImage.alt = \"Product image\"; \n            }\n        }\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
